- name: Install n98-magerun
  shell: curl -o n98-magerun.phar https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar

- name: Update permissions on n98-magerun
  shell: chmod +x ./n98-magerun.phar

- name: Move n98-magerun
  shell: mv n98-magerun.phar /usr/local/bin/n98-magerun.phar creates=/usr/local/bin/n98-magerun.phar
