---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx-full state=latest

- name: Change default nginx configuration
  sudo: yes
  template: src=nginx.tpl dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Change default nginx site
  sudo: yes
  template: src=default.tpl dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
